import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Next Mart",
  description: "Generated by create next app",
};

import React from "react";
import Link from "next/link";

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ko">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white dark:bg-gray-900 text-gray-800 dark:text-gray-100`}>
        <nav className="bg-white dark:bg-gray-800 shadow fixed top-0 w-full z-50">
          <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
            <div className="flex justify-between items-center h-16">

              {/* 로고 */}
              <div className="text-lg font-bold">
                <Link href="/">Next Mart</Link>
              </div>

              {/* 햄버거 메뉴 토글 (모바일용) */}
              <div className="md:hidden">
                <input type="checkbox" id="menu-toggle" className="hidden peer" />
                <label htmlFor="menu-toggle" className="cursor-pointer">
                  <div className="w-6 h-0.5 bg-gray-800 dark:bg-white mb-1" />
                  <div className="w-6 h-0.5 bg-gray-800 dark:bg-white mb-1" />
                  <div className="w-6 h-0.5 bg-gray-800 dark:bg-white" />
                </label>
              </div>

              {/* 데스크탑 메뉴 */}
              <div className="hidden md:flex space-x-6 w-50 justify-between">
                <Link href="/" className="hover:text-blue-500">홈</Link>
                <Link href="/about" className="hover:text-blue-500">소개</Link>
                <Link href="/contact" className="hover:text-blue-500">문의</Link>
              </div>
            </div>

            {/* 모바일 메뉴 드롭다운 */}
            <div className="peer-checked:block hidden md:hidden mt-2 space-y-2 pb-4">
              <Link href="/" className="block hover:text-blue-500">홈</Link>
              <Link href="/about" className="block hover:text-blue-500">소개</Link>
              <Link href="/contact" className="block hover:text-blue-500">문의</Link>
            </div>
          </div>
        </nav>

        {/* 페이지 콘텐츠 */}
        <div className="h-16"></div>
        <main className="px-8 min-h-screen">
          <div className="text-2xl font-bold border">
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
