import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import React from "react";
import Link from "next/link";

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ko">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-50 min-h-screen`}
      >
        <div className="flex flex-col min-h-screen">
          <header className="bg-black shadow">
            <div className="container mx-auto px-4 py-4 flex items-center justify-between">
              <h1 className="text-2xl font-bold">Next-Mart</h1>
              <nav>
                <ul className="flex space-x-6">
                  <li>
                    <Link
                      href="/"
                      className="text-white hover:text-blue-600 transition"
                    >
                      Home
                    </Link>
                  </li>
                  <li>
                    <Link
                      href="/about"
                      className="text-gray-700 hover:text-blue-600 transition"
                    >
                      About
                    </Link>
                  </li>
                  <li>
                    <Link
                      href="/products"
                      className="text-gray-700 hover:text-blue-600 transition"
                    >
                      Products
                    </Link>
                  </li>
                  <li>
                    <Link
                      href="/contact"
                      className="text-gray-700 hover:text-blue-600 transition"
                    >
                      Contact
                    </Link>
                  </li>
                </ul>
              </nav>
            </div>
          </header>

          <main className="flex-1 container mx-auto px-4 py-8">{children}</main>

          <footer className="bg-white border-t py-4">
            <div className="container mx-auto px-4 text-center text-gray-500 text-sm">
              &copy; 2025 My Shopping Mall. All Rights Reserved.
            </div>
          </footer>
        </div>
      </body>
    </html>
  );
}
